### ISSUE TITLE
Installer not working anymore

### ISSUE THREAD

**Issue by jaapjolman** [anomalylabs/streams#9] opened 2014-12-22 10:10 UTC
Hey i tried the installer and got this error

ErrorException in FormBuilder.php line 99: Undefined property: Anomaly\Streams\Addon\Distribution\Streams\Ui\Form\InstallerFormBuilder::$handleCommand

    in FormBuilder.php line 99
    at HandleExceptions->handleError('8', 'Undefined property: Anomaly\Streams\Addon\Distribution\Streams\Ui\Form\InstallerFormBuilder::$handleCommand', '/var/sites/radius.odin-ict.nl/vendor/anomaly/streams-platform/src/Ui/Form/FormBuilder.php', '99', array('entry' => null, 'this' => object(InstallerFormBuilder))) in FormBuilder.php line 99
    at FormBuilder->build(null) in FormBuilder.php line 110
    at FormBuilder->make(null) in FormBuilder.php line 125
    at FormBuilder->render() in InstallerController.php line 11
    at InstallerController->index(object(InstallerFormBuilder))
    at call_user_func_array(array(object(InstallerController), 'index'), array(object(InstallerFormBuilder))) in Controller.php line 243
    at Controller->callAction('index', array(object(InstallerFormBuilder))) in ControllerDispatcher.php line 161
    at ControllerDispatcher->call(object(InstallerController), object(Route), 'index') in ControllerDispatcher.php line 106
    at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Stack.php line 111
    at Stack->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Stack.php line 82
    at Stack->then(object(Closure)) in ControllerDispatcher.php line 107
    at ControllerDispatcher->callWithinStack(object(InstallerController), object(Route), object(Request), 'index') in ControllerDispatcher.php line 66
    at ControllerDispatcher->dispatch(object(Route), object(Request), 'Anomaly\Streams\Addon\Distribution\Streams\Http\Controller\InstallerController', 'index') in Route.php line 197
    at Route->runWithCustomDispatcher(object(Request)) in Route.php line 130
    at Route->run(object(Request)) in Router.php line 671
    at Router->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Stack.php line 111
    at Stack->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Stack.php line 82
    at Stack->then(object(Closure)) in Router.php line 672
    at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 642
    at Router->dispatchToRoute(object(Request)) in Router.php line 600
    at Router->dispatch(object(Request)) in Kernel.php line 154
    at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Stack.php line 111
    at Stack->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 55
    at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Stack.php line 96
    at Stack->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 52
    at StartSession->handle(object(Request), object(Closure)) in Stack.php line 96
    at Stack->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 36
    at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Stack.php line 96
    at Stack->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 40
    at EncryptCookies->handle(object(Request), object(Closure)) in Stack.php line 96
    at Stack->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 42
    at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Stack.php line 96
    at Stack->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Stack.php line 82
    at Stack->then(object(Closure)) in Kernel.php line 107
    at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 82
    at Kernel->handle(object(Request)) in index.php line 51

**Comment by londoh** [comment] 2015-01-08 13:05
fwiw I just ran install and got a couple blow ups:

```
Generating autoload files
exception 'ReflectionException' with message 'Class cebe\markdown\Markdown does not exist' in /home/colin/MyDocs/Development/www/laranom/streams/vendor/laravel/framework/src/Illuminate/Container/Container.php:802
```

and then with cebe/markdown

```
has an invalid name.' in /home/colin/MyDocs/Development/www/laranom/streams/vendor/rcrowe/twigbridge/src/Twig/Loader.php:81
```

**Comment by iknowfoobar** [comment] 2015-01-08 16:23
@londoh I was getting this too and I think this is to do with the composer.lock file committed to the repo being out of sync with the committed composer.json. 

If you run a composer update the problem is fixed.

**Comment by RyanThompson** [comment] 2015-01-08 20:30
Ill see about updating this.

**Closed** 2015-01-08 20:30 UTC
